# Generated by Django 4.0.3 on 2022-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_year',
            field=models.IntegerField(null=True),
        ),
    ]
